In [1]:
number = 15

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [4]:
my_list = [1, 2, 3]

### Numpy

In [5]:
# pip install numpy
# pip3 install numpy

In [8]:
import numpy as np

In [9]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
array_a = np.array([1,2,3,4])

In [12]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [13]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
array_a[0]

1

In [15]:
array_b[-1]

2.0

In [16]:
array_a[:2]

array([1, 2])

In [17]:
array_a.dtype

dtype('int32')

In [18]:
array_b.dtype

dtype('float64')

In [19]:
empty_array = np.array([])

In [21]:
empty_array.dtype

dtype('float64')

In [22]:
np.array([1,2,3,4], dtype=np.float_)

array([1., 2., 3., 4.])

In [23]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [24]:
array_c = np.array(["ada", "lovelace"])

In [25]:
array_c.dtype

dtype('<U8')

### Dimensions and shapes

In [26]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]   
])

In [27]:
array_a.shape

(4,)

In [28]:
my_array.shape

(2, 3)

In [29]:
array_a.shape

(4,)

In [30]:
array_a.ndim

1

In [31]:
my_array.ndim

2

In [32]:
my_array.size

6

In [33]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [34]:
my_array.ndim

3

In [35]:
my_array.shape

(2, 2, 3)

In [36]:
my_array.size

12

### indexing and slicing

In [37]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [38]:
my_array[1]

array([4, 5, 6])

In [39]:
my_array[1][0]

4

In [40]:
my_array[1, 0]

4

In [41]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [43]:
my_array[1] = np.array([10, 10, 10])

In [44]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [45]:
my_array[2] = 99 
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [46]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [50]:
my_array = np.arange(0, 10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((5, 2))

In [ ]:
np.ones((2, 5, 3))

In [ ]:
np.eye((5, 5))

In [55]:
my_array = np.random.random((5,2))

In [56]:
my_array

array([[0.75869671, 0.56204009],
       [0.26679795, 0.93135827],
       [0.96689044, 0.16632361],
       [0.66171792, 0.11949931],
       [0.31813384, 0.88677001]])

In [57]:
np.random.randint(100, size=(5, 5))

array([[81,  5, 40, 64, 20],
       [32,  4, 84,  5, 41],
       [49, 99, 80, 87,  4],
       [90, 51, 61, 81, 68],
       [66, 28, 36, 38, 25]])

In [58]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [59]:
# any(), all(), full(), concatenate()

In [62]:
np.any([2,4,6])

True

In [ ]:
any.all()

In [61]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [64]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array1 = array1.reshape(2, 5)

In [66]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.concatenate([array1, array1], axis = 1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### Statistics

In [69]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
array1.sum(), array1.mean(), array1.std(), array1.var()

(45, 4.5, 2.8722813232690143, 8.25)

In [71]:
array1.sum(axis=1), array1.sum(axis=0)

(array([10, 35]), array([ 5,  7,  9, 11, 13]))

In [72]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
array2 = np.arange(0,10)
array2 = array2.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [76]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [77]:
a[0], a[-1]

(0, 3)

In [78]:
a[[0, -1]]

array([0, 3])

In [79]:
a[[True, False, False, True]]

array([0, 3])

In [80]:
a >= 2

array([False, False,  True,  True])

In [81]:
a[a >= 2]

array([2, 3])

In [82]:
a[a > a.mean()]

array([2, 3])

In [83]:
a[~(a > a.mean())]

array([0, 1])

In [84]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [85]:
a[(a <= 2) & (a %2 == 0)]

array([0, 2])

In [88]:
# 100'e kadar rastgele tamsayılardan oluşan 3,3 bir matris oluşturun.
# 30'dan büyük olanları boolean yöntemi ile filtreleyin.
m = np.random.randint(0, 100, size=(3, 3))
m

array([[66, 76, 62],
       [45, 27,  4],
       [25, 90, 22]])

In [89]:
m[(m>30)]

array([66, 76, 62, 45, 90])

In [90]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
array1 = my_array.reshape(5,2)
array2 = my_array.reshape(2,5)

In [91]:
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [92]:
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
np.dot(array1, array2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [94]:
array2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [95]:
import sys

In [96]:
sys.getsizeof(10)

28

In [98]:
sys.getsizeof(1000**100)

160

In [99]:
np.dtype(int).itemsize

4

In [100]:
np.dtype(np.int8).itemsize

1

In [101]:
np.dtype(float).itemsize

8

In [102]:
sys.getsizeof([1,2,3])

88

In [103]:
np.array([1,2,3]).nbytes

12

In [104]:
my_list = list(range(100000))

In [105]:
my_array = np.arange(100000)

In [106]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [107]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 31.2 ms
Wall time: 55.9 ms


333328333350000